name: Sonar Location Saver

on:
  workflow_run:
    workflows: ["Build Location Saver"]
    types: [completed]
  workflow_dispatch:

jobs:
  sonar:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: hendafarhani/microGo/.github/workflows/sonar-analysis.yml@main
    with:
      java_version: "21"
      sonar_project_key: "hendafarhani_location-saver"
      sonar_organization: "hendafarhani"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
